name: Build
on:
  pull_request:
  workflow_dispatch:
    inputs:
      clean:
        type: boolean
        default: false
        description: "clean"

env:
  CLEAN: ${{ github.event.inputs.clean || false }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-unity-version:
    name: Get Unity Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          clean: "${{ env.CLEAN }}"
      - name: Get Unity version
        run: |
          echo "UNITY_VERSION=$(grep "m_EditorVersion:" < ProjectSettings/ProjectVersion.txt | cut -d" " -f2)" >> "${GITHUB_ENV}"

  android:
    name: Android
    needs: get-unity-version
    runs-on: [self-hosted, macOS]
    steps:
      - name: Switch workspace
        uses: DeNA/setup-job-workspace-action@fea4ef4d011492fe235833241acbb4fced82da27
      - uses: actions/checkout@v4
        with:
          clean: "${{ env.CLEAN }}"
      - name: Get Unity version
        run: |
          echo "UNITY_VERSION=$(grep "m_EditorVersion:" < ProjectSettings/ProjectVersion.txt | cut -d" " -f2)" >> "${GITHUB_ENV}"
      - name: Android Build
        env:
          ANDROID_NDK_ROOT: "/Applications/Unity/Hub/Editor/${UNITY_VERSION}/PlaybackEngines/AndroidPlayer/NDK"
        run: |
          /Applications/Unity/Hub/Editor/"${UNITY_VERSION}"/Unity.app/Contents/MacOS/Unity \
            -quit \
            -batchmode \
            -nographics \
            -projectPath "$(pwd)" \
            -executeMethod Editor.BuildEntryPoint.BuildAndroid

  ios:
    name: iOS
    needs: get-unity-version
    runs-on: [self-hosted, macOS]
    steps:
      - name: Switch workspace
        uses: DeNA/setup-job-workspace-action@fea4ef4d011492fe235833241acbb4fced82da27
      - uses: actions/checkout@v4
        with:
          clean: "${{ env.CLEAN }}"
      - name: Get Unity version
        run: |
          echo "UNITY_VERSION=$(grep "m_EditorVersion:" < ProjectSettings/ProjectVersion.txt | cut -d" " -f2)" >> "${GITHUB_ENV}"
      - name: iOS Build
        run: |
          /Applications/Unity/Hub/Editor/"${UNITY_VERSION}"/Unity.app/Contents/MacOS/Unity \
            -quit \
            -batchmode \
            -nographics \
            -projectPath "$(pwd)" \
            -executeMethod Editor.BuildEntryPoint.BuildIOS

  macos:
    name: macOS
    needs: get-unity-version
    runs-on: [self-hosted, macOS]
    steps:
      - name: Switch workspace
        uses: DeNA/setup-job-workspace-action@fea4ef4d011492fe235833241acbb4fced82da27
      - uses: actions/checkout@v4
        with:
          clean: "${{ env.CLEAN }}"
      - name: Get Unity version
        run: |
          echo "UNITY_VERSION=$(grep "m_EditorVersion:" < ProjectSettings/ProjectVersion.txt | cut -d" " -f2)" >> "${GITHUB_ENV}"
      - name: macOS Build
        run: |
          /Applications/Unity/Hub/Editor/"${UNITY_VERSION}"/Unity.app/Contents/MacOS/Unity \
            -quit \
            -batchmode \
            -nographics \
            -projectPath "$(pwd)" \
            -executeMethod Editor.BuildEntryPoint.BuildMacOS

  webgl:
    name: WebGL
    needs: get-unity-version
    runs-on: [ self-hosted, macOS ]
    steps:
      - name: Switch workspace
        uses: DeNA/setup-job-workspace-action@fea4ef4d011492fe235833241acbb4fced82da27
      - uses: actions/checkout@v4
        with:
          clean: "${{ env.CLEAN }}"
      - name: Get Unity version
        run: |
          echo "UNITY_VERSION=$(grep "m_EditorVersion:" < ProjectSettings/ProjectVersion.txt | cut -d" " -f2)" >> "${GITHUB_ENV}"
      - name: macOS Build
        run: |
          /Applications/Unity/Hub/Editor/"${UNITY_VERSION}"/Unity.app/Contents/MacOS/Unity \
            -quit \
            -batchmode \
            -nographics \
            -projectPath "$(pwd)" \
            -executeMethod Editor.BuildEntryPoint.BuildWebGL
