name: Build
on:
  pull_request:
  workflow_dispatch:
    inputs:
      clean:
        type: boolean
        default: false
        description: "clean"

env:
  CLEAN: ${{ github.event.inputs.clean || false }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    runs-on: ubuntu-latest
    steps:
      - name: Switch workspace
        uses: DeNA/setup-job-workspace-action@v2
      - uses: actions/checkout@v4
        with:
          clean: "${{ env.CLEAN }}"
      - name: Get Unity version
        run: |
          echo "UNITY_VERSION=$(grep "m_EditorVersion:" < ProjectSettings/ProjectVersion.txt | cut -d" " -f2)" >> "${GITHUB_ENV}"
      - name: Android Build
        env:
          ANDROID_NDK_ROOT: "/Applications/Unity/Hub/Editor/${UNITY_VERSION}/PlaybackEngines/AndroidPlayer/NDK"
        run: |
          /Applications/Unity/Hub/Editor/"${UNITY_VERSION}"/Unity.app/Contents/MacOS/Unity \
            -quit \
            -batchmode \
            -nographics \
            -projectPath "$(pwd)" \
            -buildTarget Android \
            -executeMethod Editor.BuildEntryPoint.Build \
